# Generated by Django 2.2.6 on 2020-02-01 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191111_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='summary',
            new_name='tech_stack',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='tile',
            field=models.CharField(default='Project Name', max_length=100),
        ),
    ]
