# Generated by Django 2.2.6 on 2020-02-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200201_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tile',
            new_name='title',
        ),
    ]
