# Generated by Django 2.2.6 on 2020-03-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
