# Generated by Django 2.2.6 on 2020-04-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='caption',
            field=models.CharField(default='Image 1', max_length=50),
        ),
    ]
