# Generated by Django 2.2.6 on 2020-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectimages_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='caption',
            field=models.CharField(default='Image 1', max_length=100),
        ),
    ]
