# Generated by Django 2.2.6 on 2020-02-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-start_date']},
        ),
    ]
